// This simple executable tool is used by go generate
// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package main

import (
	"io"
	"io/ioutil"
	"os"
	"strings"
)

// Reads all .json files in the current folder
// and encodes them as strings literals in textfiles.go
func main() {
	fs, _ := ioutil.ReadDir(".")
	out, _ := os.Create("swagger.pb.go")
	defer out.Close()

	out.Write([]byte(`// Code generated by go generate. DO NOT EDIT
// source: profile.swagger.json
package pb

const (

`))
	for _, f := range fs {
		if strings.HasSuffix(f.Name(), ".json") {
			name := strings.TrimPrefix(f.Name(), "profile.")
			out.Write([]byte(strings.TrimSuffix(name, ".json") + " = `"))
			f, _ := os.Open(f.Name())
			io.Copy(out, f)
			out.Write([]byte("`\n"))
			f.Close()
		}
	}
	out.Write([]byte(")\n"))
}
