// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package functest

import (
	"fmt"

	pb "github.com/gomeet-examples/svc-profile/pb"
)

func TestVersion(config FunctionalTestConfig) []TestFailure {
	var failures []TestFailure

	client, ctx, err := grpcClient(config)
	if err != nil {
		failures = append(failures, TestFailure{Procedure: "Version", Message: fmt.Sprintf("gRPC client initialization error (%v)", err)})
		return failures
	}
	defer client.Close()

	req := &pb.EmptyMessage{}
	res, err := client.GetGRPCClient().Version(ctx, req)
	if err != nil {
		// one retry if the connection is unavailable
		client, ctx, err := grpcClient(config)
		if err != nil {
			failures = append(failures, TestFailure{Procedure: "Version", Message: fmt.Sprintf("gRPC client initialization error (%v)", err)})
			return failures
		}
		defer client.Close()
		res, err = client.GetGRPCClient().Version(ctx, req)
		if err != nil {
			failures = append(failures, TestFailure{Procedure: "Version", Message: fmt.Sprintf("call error (%v)", err)})
			return failures
		}
	}

	return testVersionResponse(req, res)
}
