// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
// to extend the profileHTTPController struct use a new file
package service

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	log "github.com/sirupsen/logrus"

	pb "github.com/gomeet-examples/svc-profile/pb"
)

type profileHTTPController struct{}

func newProfileHTTPController() *profileHTTPController {
	return new(profileHTTPController)
}

func (s profileHTTPController) Status(w http.ResponseWriter, r *http.Request) {
	log.Info("profileHTTPController.Status")
	fmt.Fprintf(w, "OK")
}

func (s profileHTTPController) Swagger(w http.ResponseWriter, r *http.Request) {
	log.Info("profileHTTPController.Swagger")
	w.Header().Set("Content-Type", "application/json")
	io.Copy(w, strings.NewReader(pb.Swagger))
}

func (s profileHTTPController) Version(w http.ResponseWriter, r *http.Request) {
	log.Info("profileHTTPController.Version")
	v := pb.VersionResponse{
		Name:    name,
		Version: version,
	}
	output, err := json.Marshal(v)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Write(output)
}
