// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package service

//import (
//	// SUB-SERVICES DEFINITION : import-Client
//	// svc{{SubServiceNamePascalCase}}Client "github.com/gomeet-examples/svc-{{SubServiceNameKebabCase}}/client"
// END SUB-SERVICES DEFINITION : import-client
//)

const grpcTimeout = 5

// SUB-SERVICES DEFINITION : func-init
// //init{{SubServiceNamePascalCase}} Client initializes the gRPC client connecting to the {{SubServiceNamePascalCase}} service.
// func (s *profileServer) init{{SubServiceNamePascalCase}}Client() error {
//   if s.svc{{SubServiceNamePascalCase}}GrpcClient != nil {
//     return nil
//   }
//
//   cli, err := svc{{SubServiceNamePascalCase}}Client.NewGomeetClient(s.svc{{SubServiceNamePascalCase}}Address,
//     grpcTimeout,
//     s.caCertificate,
//     s.certificate,
//     s.privateKey,
//   )
//
//   if err != nil {
//     return err
//   }
//
//   s.svc{{SubServiceNamePascalCase}}GrpcClient = cli.GetGRPCClient()
//
//   return nil
// }

// END SUB-SERVICES DEFINITION : func-init
