// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package cmd

import (
	"strings"

	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"

	rcli "github.com/gomeet-examples/svc-profile/cmd/remotecli"
)

// cliCmd represents the cli command
var (
	cliAddress string
	cliCmd     = &cobra.Command{
		Use:   "cli [gRPC service] [args...]",
		Short: "Cli on svc-profile service",
		Long: `Use this command cli svc-profile service

Example :
  $ svc-profile cli version
  $ svc-profile cli services_status
  $ svc-profile cli create <gender [UNKNOW|MALE|FEMALE]> <email [string]> <name [string]> <birthday [string]>
  $ svc-profile cli read <uuid [string]>
  $ svc-profile cli list <page_number [uint32]> <page_size [uint32]> <order [string]> <exclude_soft_deleted [bool]> <soft_deleted_only [bool]> <gender [UNKNOW|MALE|FEMALE]>
  $ svc-profile cli update <uuid [string]> <gender [UNKNOW|MALE|FEMALE]> <email [string]> <name [string]> <birthday [string]> <created_at [string]> <updated_at [string]> <deleted_at [string]>
  $ svc-profile cli soft_delete <uuid [string]>
  $ svc-profile cli hard_delete <uuid [string]>
  $ svc-profile cli --address localhost:42000 version

`,
		Run: cli,
	}
)

func init() {
	RootCmd.AddCommand(cliCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// Port flag
	cliCmd.PersistentFlags().StringVar(&cliAddress, "address", "localhost:13000", "Server address")

	// CA certificate
	cliCmd.PersistentFlags().StringVar(&caCertificate, "ca", "", "X.509 certificate of the Certificate Authority (required for gRPC TLS support)")

	// gRPC client certificate
	cliCmd.PersistentFlags().StringVar(&clientCertificate, "cert", "", "X.509 certificate of the gRPC client (required for gRPC TLS support)")

	// gRPC client private key
	cliCmd.PersistentFlags().StringVar(&clientPrivateKey, "key", "", "RSA private key of the gRPC client (required for gRPC TLS support)")

	// gRPC timeout
	cliCmd.PersistentFlags().IntVar(&timeoutSeconds, "timeout", 5, "gRPC timeout in seconds")

	// JSON Web Token
	cliCmd.PersistentFlags().StringVar(&jwtToken, "jwt", "", "JSON Web Token")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// cliCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")

}

func cli(cmd *cobra.Command, args []string) {
	// Cli must have at least one argument
	if len(args) < 1 {
		log.Fatal("Bad arguments")
	}

	// Initialize remote cli
	c, err := rcli.NewRemoteCli(
		svc.Name,
		svc.Version,
		rcli.CliCall,
		cliAddress,
		timeoutSeconds,
		caCertificate,
		clientCertificate,
		clientPrivateKey,
		jwtToken,
	)
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	// Defer remote cli closing
	defer c.Close()

	// Convert arguments to string
	line := strings.Join(args, " ")

	// Evaluate arguments string
	ok, err := c.Eval(line)
	if err != nil {
		log.Fatal(err)
	}
	log.Info(ok)
}
