// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package cmd

import (
	"fmt"
	"os"

	"github.com/gomeet-examples/svc-profile/models"

	"github.com/spf13/cobra"
)

var (
	migrateCmd = &cobra.Command{
		Use:   "migrate",
		Short: "Migrates the user database schema",
		Run:   migrateSchema,
	}
	mysqlMigrateDataSourceName string
)

func init() {
	RootCmd.AddCommand(migrateCmd)

	// Mysql data source name: https://github.com/go-sql-driver/mysql#dsn-data-source-name
	migrateCmd.PersistentFlags().StringVar(&mysqlMigrateDataSourceName, "mysql-dsn", "", "Mysql connection informations (USERNAME:PASSWORD@tcp(HOSTNAME:3306)/DBNAME)")
}

func migrateSchema(cmd *cobra.Command, args []string) {
	var (
		err    error
		hasOne bool
	)

	// initialize the mysql database schema
	if mysqlMigrateDataSourceName != "" {
		hasOne = true
		err = models.MigrateSchema(mysqlMigrateDataSourceName)

		if err != nil {
			fmt.Printf("Mysql schema migration error: %s\n", err)
			os.Exit(1)
		}
		fmt.Println("Mysql database schema was successfully migrated")
	}

	if !hasOne {
		fmt.Println("No migration found")
		fmt.Println("Use one of flags :")
		fmt.Println("   --mysql-dsn")
	}
}
