// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/profile.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/profile.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	ProfileInfo
	ProfileRequest
	ProfileResponse
	ProfileCreationRequest
	ProfileListRequest
	ProfileList
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Genders int32

const (
	Genders_UNKNOW Genders = 0
	Genders_MALE   Genders = 1
	Genders_FEMALE Genders = 2
)

var Genders_name = map[int32]string{
	0: "UNKNOW",
	1: "MALE",
	2: "FEMALE",
}
var Genders_value = map[string]int32{
	"UNKNOW": 0,
	"MALE":   1,
	"FEMALE": 2,
}

func (x Genders) String() string {
	return proto.EnumName(Genders_name, int32(x))
}
func (Genders) EnumDescriptor() ([]byte, []int) { return fileDescriptorProfile, []int{0} }

type ServiceStatus_Status int32

const (
	ServiceStatus_OK          ServiceStatus_Status = 0
	ServiceStatus_UNAVAILABLE ServiceStatus_Status = 1
)

var ServiceStatus_Status_name = map[int32]string{
	0: "OK",
	1: "UNAVAILABLE",
}
var ServiceStatus_Status_value = map[string]int32{
	"OK":          0,
	"UNAVAILABLE": 1,
}

func (x ServiceStatus_Status) String() string {
	return proto.EnumName(ServiceStatus_Status_name, int32(x))
}
func (ServiceStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorProfile, []int{2, 0}
}

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{0} }

// VersionMessage represents a version message
type VersionResponse struct {
	// Id represents the message identifier.
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{1} }

func (m *VersionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// SeviceStatus represents a sub services status message
type ServiceStatus struct {
	Name    string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status  ServiceStatus_Status `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.gomeetexamples.profile.ServiceStatus_Status" json:"status,omitempty"`
	EMsg    string               `protobuf:"bytes,4,opt,name=e_msg,json=eMsg,proto3" json:"e_msg,omitempty"`
}

func (m *ServiceStatus) Reset()                    { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string            { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()               {}
func (*ServiceStatus) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{2} }

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceStatus) GetStatus() ServiceStatus_Status {
	if m != nil {
		return m.Status
	}
	return ServiceStatus_OK
}

func (m *ServiceStatus) GetEMsg() string {
	if m != nil {
		return m.EMsg
	}
	return ""
}

// ServicesStatusList is the sub services status list
type ServicesStatusList struct {
	Services []*ServiceStatus `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesStatusList) Reset()                    { *m = ServicesStatusList{} }
func (m *ServicesStatusList) String() string            { return proto.CompactTextString(m) }
func (*ServicesStatusList) ProtoMessage()               {}
func (*ServicesStatusList) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{3} }

func (m *ServicesStatusList) GetServices() []*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

// ProfileInfo encodes information about a profile.
type ProfileInfo struct {
	Uuid     string  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Gender   Genders `protobuf:"varint,2,opt,name=gender,proto3,enum=grpc.gomeetexamples.profile.Genders" json:"gender,omitempty"`
	Email    string  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name     string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Birthday string  `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (m *ProfileInfo) Reset()                    { *m = ProfileInfo{} }
func (m *ProfileInfo) String() string            { return proto.CompactTextString(m) }
func (*ProfileInfo) ProtoMessage()               {}
func (*ProfileInfo) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{4} }

func (m *ProfileInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProfileInfo) GetGender() Genders {
	if m != nil {
		return m.Gender
	}
	return Genders_UNKNOW
}

func (m *ProfileInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileInfo) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

// ProfileRequest encodes a profile identifier.
type ProfileRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (m *ProfileRequest) Reset()                    { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()               {}
func (*ProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{5} }

func (m *ProfileRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// ProfileResponse encodes the result of a profile operation.
type ProfileResponse struct {
	Ok   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Info *ProfileInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *ProfileResponse) Reset()                    { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()               {}
func (*ProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{6} }

func (m *ProfileResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ProfileResponse) GetInfo() *ProfileInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// ProfileCreationRequest encodes a profile creation request.
type ProfileCreationRequest struct {
	Gender   Genders `protobuf:"varint,1,opt,name=gender,proto3,enum=grpc.gomeetexamples.profile.Genders" json:"gender,omitempty"`
	Email    string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name     string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Birthday string  `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (m *ProfileCreationRequest) Reset()                    { *m = ProfileCreationRequest{} }
func (m *ProfileCreationRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileCreationRequest) ProtoMessage()               {}
func (*ProfileCreationRequest) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{7} }

func (m *ProfileCreationRequest) GetGender() Genders {
	if m != nil {
		return m.Gender
	}
	return Genders_UNKNOW
}

func (m *ProfileCreationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileCreationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileCreationRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

// ProfileListRequest encodes a set of criteria for the retrieval of a list of profiles.
type ProfileListRequest struct {
	PageNumber uint32  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize   uint32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Gender     Genders `protobuf:"varint,3,opt,name=gender,proto3,enum=grpc.gomeetexamples.profile.Genders" json:"gender,omitempty"`
}

func (m *ProfileListRequest) Reset()                    { *m = ProfileListRequest{} }
func (m *ProfileListRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileListRequest) ProtoMessage()               {}
func (*ProfileListRequest) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{8} }

func (m *ProfileListRequest) GetPageNumber() uint32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ProfileListRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ProfileListRequest) GetGender() Genders {
	if m != nil {
		return m.Gender
	}
	return Genders_UNKNOW
}

// ProfileList encodes the result of a ProfileListRequest.
type ProfileList struct {
	ResultSetSize uint32         `protobuf:"varint,1,opt,name=result_set_size,json=resultSetSize,proto3" json:"result_set_size,omitempty"`
	HasMore       bool           `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Profiles      []*ProfileInfo `protobuf:"bytes,3,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *ProfileList) Reset()                    { *m = ProfileList{} }
func (m *ProfileList) String() string            { return proto.CompactTextString(m) }
func (*ProfileList) ProtoMessage()               {}
func (*ProfileList) Descriptor() ([]byte, []int) { return fileDescriptorProfile, []int{9} }

func (m *ProfileList) GetResultSetSize() uint32 {
	if m != nil {
		return m.ResultSetSize
	}
	return 0
}

func (m *ProfileList) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *ProfileList) GetProfiles() []*ProfileInfo {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "grpc.gomeetexamples.profile.EmptyMessage")
	proto.RegisterType((*VersionResponse)(nil), "grpc.gomeetexamples.profile.VersionResponse")
	proto.RegisterType((*ServiceStatus)(nil), "grpc.gomeetexamples.profile.ServiceStatus")
	proto.RegisterType((*ServicesStatusList)(nil), "grpc.gomeetexamples.profile.ServicesStatusList")
	proto.RegisterType((*ProfileInfo)(nil), "grpc.gomeetexamples.profile.ProfileInfo")
	proto.RegisterType((*ProfileRequest)(nil), "grpc.gomeetexamples.profile.ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "grpc.gomeetexamples.profile.ProfileResponse")
	proto.RegisterType((*ProfileCreationRequest)(nil), "grpc.gomeetexamples.profile.ProfileCreationRequest")
	proto.RegisterType((*ProfileListRequest)(nil), "grpc.gomeetexamples.profile.ProfileListRequest")
	proto.RegisterType((*ProfileList)(nil), "grpc.gomeetexamples.profile.ProfileList")
	proto.RegisterEnum("grpc.gomeetexamples.profile.Genders", Genders_name, Genders_value)
	proto.RegisterEnum("grpc.gomeetexamples.profile.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
}
func (this *EmptyMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EmptyMessage)
	if !ok {
		that2, ok := that.(EmptyMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *VersionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionResponse)
	if !ok {
		that2, ok := that.(VersionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	return true
}
func (this *ServiceStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServiceStatus)
	if !ok {
		that2, ok := that.(ServiceStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.EMsg != that1.EMsg {
		return false
	}
	return true
}
func (this *ServicesStatusList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServicesStatusList)
	if !ok {
		that2, ok := that.(ServicesStatusList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Services) != len(that1.Services) {
		return false
	}
	for i := range this.Services {
		if !this.Services[i].Equal(that1.Services[i]) {
			return false
		}
	}
	return true
}
func (this *ProfileInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileInfo)
	if !ok {
		that2, ok := that.(ProfileInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Gender != that1.Gender {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Birthday != that1.Birthday {
		return false
	}
	return true
}
func (this *ProfileRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileRequest)
	if !ok {
		that2, ok := that.(ProfileRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	return true
}
func (this *ProfileResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileResponse)
	if !ok {
		that2, ok := that.(ProfileResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ok != that1.Ok {
		return false
	}
	if !this.Info.Equal(that1.Info) {
		return false
	}
	return true
}
func (this *ProfileCreationRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileCreationRequest)
	if !ok {
		that2, ok := that.(ProfileCreationRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Gender != that1.Gender {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Birthday != that1.Birthday {
		return false
	}
	return true
}
func (this *ProfileListRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileListRequest)
	if !ok {
		that2, ok := that.(ProfileListRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PageNumber != that1.PageNumber {
		return false
	}
	if this.PageSize != that1.PageSize {
		return false
	}
	if this.Gender != that1.Gender {
		return false
	}
	return true
}
func (this *ProfileList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProfileList)
	if !ok {
		that2, ok := that.(ProfileList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ResultSetSize != that1.ResultSetSize {
		return false
	}
	if this.HasMore != that1.HasMore {
		return false
	}
	if len(this.Profiles) != len(that1.Profiles) {
		return false
	}
	for i := range this.Profiles {
		if !this.Profiles[i].Equal(that1.Profiles[i]) {
			return false
		}
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Profile service

type ProfileClient interface {
	// Version method receives no paramaters and returns a version message.
	Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error)
	// Create attempts to create a new profile.
	Create(ctx context.Context, in *ProfileCreationRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	// Read returns information about an existing profile.
	Read(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileInfo, error)
	// List returns a list of profiles matching a set of criteria.
	List(ctx context.Context, in *ProfileListRequest, opts ...grpc.CallOption) (*ProfileList, error)
	// Update attempts to update an existing profile.
	Update(ctx context.Context, in *ProfileInfo, opts ...grpc.CallOption) (*ProfileResponse, error)
	// SoftDelete attempts to delete an existing profile logically.
	SoftDelete(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	// HardDelete attempts to delete an existing profile physically.
	HardDelete(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error) {
	out := new(ServicesStatusList)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/ServicesStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Create(ctx context.Context, in *ProfileCreationRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Read(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileInfo, error) {
	out := new(ProfileInfo)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) List(ctx context.Context, in *ProfileListRequest, opts ...grpc.CallOption) (*ProfileList, error) {
	out := new(ProfileList)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Update(ctx context.Context, in *ProfileInfo, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) SoftDelete(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/SoftDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) HardDelete(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.profile.Profile/HardDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profile service

type ProfileServer interface {
	// Version method receives no paramaters and returns a version message.
	Version(context.Context, *EmptyMessage) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(context.Context, *EmptyMessage) (*ServicesStatusList, error)
	// Create attempts to create a new profile.
	Create(context.Context, *ProfileCreationRequest) (*ProfileResponse, error)
	// Read returns information about an existing profile.
	Read(context.Context, *ProfileRequest) (*ProfileInfo, error)
	// List returns a list of profiles matching a set of criteria.
	List(context.Context, *ProfileListRequest) (*ProfileList, error)
	// Update attempts to update an existing profile.
	Update(context.Context, *ProfileInfo) (*ProfileResponse, error)
	// SoftDelete attempts to delete an existing profile logically.
	SoftDelete(context.Context, *ProfileRequest) (*ProfileResponse, error)
	// HardDelete attempts to delete an existing profile physically.
	HardDelete(context.Context, *ProfileRequest) (*ProfileResponse, error)
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Version(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_ServicesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).ServicesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/ServicesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).ServicesStatus(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Create(ctx, req.(*ProfileCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Read(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).List(ctx, req.(*ProfileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Update(ctx, req.(*ProfileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_SoftDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).SoftDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/SoftDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).SoftDelete(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_HardDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).HardDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.profile.Profile/HardDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).HardDelete(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gomeetexamples.profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Profile_Version_Handler,
		},
		{
			MethodName: "ServicesStatus",
			Handler:    _Profile_ServicesStatus_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Profile_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Profile_Read_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Profile_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Profile_Update_Handler,
		},
		{
			MethodName: "SoftDelete",
			Handler:    _Profile_SoftDelete_Handler,
		},
		{
			MethodName: "HardDelete",
			Handler:    _Profile_HardDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/profile.proto",
}

func NewPopulatedEmptyMessage(r randyProfile, easy bool) *EmptyMessage {
	this := &EmptyMessage{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedVersionResponse(r randyProfile, easy bool) *VersionResponse {
	this := &VersionResponse{}
	this.Name = string(randStringProfile(r))
	this.Version = string(randStringProfile(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServiceStatus(r randyProfile, easy bool) *ServiceStatus {
	this := &ServiceStatus{}
	this.Name = string(randStringProfile(r))
	this.Version = string(randStringProfile(r))
	this.Status = ServiceStatus_Status([]int32{0, 1}[r.Intn(2)])
	this.EMsg = string(randStringProfile(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServicesStatusList(r randyProfile, easy bool) *ServicesStatusList {
	this := &ServicesStatusList{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Services = make([]*ServiceStatus, v1)
		for i := 0; i < v1; i++ {
			this.Services[i] = NewPopulatedServiceStatus(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileInfo(r randyProfile, easy bool) *ProfileInfo {
	this := &ProfileInfo{}
	this.Uuid = string(randStringProfile(r))
	this.Gender = Genders([]int32{0, 1, 2}[r.Intn(3)])
	this.Email = string(randStringProfile(r))
	this.Name = string(randStringProfile(r))
	this.Birthday = string(randStringProfile(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileRequest(r randyProfile, easy bool) *ProfileRequest {
	this := &ProfileRequest{}
	this.Uuid = string(randStringProfile(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileResponse(r randyProfile, easy bool) *ProfileResponse {
	this := &ProfileResponse{}
	this.Ok = bool(bool(r.Intn(2) == 0))
	if r.Intn(10) != 0 {
		this.Info = NewPopulatedProfileInfo(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileCreationRequest(r randyProfile, easy bool) *ProfileCreationRequest {
	this := &ProfileCreationRequest{}
	this.Gender = Genders([]int32{0, 1, 2}[r.Intn(3)])
	this.Email = string(randStringProfile(r))
	this.Name = string(randStringProfile(r))
	this.Birthday = string(randStringProfile(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileListRequest(r randyProfile, easy bool) *ProfileListRequest {
	this := &ProfileListRequest{}
	this.PageNumber = uint32(r.Uint32())
	this.PageSize = uint32(r.Uint32())
	this.Gender = Genders([]int32{0, 1, 2}[r.Intn(3)])
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProfileList(r randyProfile, easy bool) *ProfileList {
	this := &ProfileList{}
	this.ResultSetSize = uint32(r.Uint32())
	this.HasMore = bool(bool(r.Intn(2) == 0))
	if r.Intn(10) != 0 {
		v2 := r.Intn(5)
		this.Profiles = make([]*ProfileInfo, v2)
		for i := 0; i < v2; i++ {
			this.Profiles[i] = NewPopulatedProfileInfo(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyProfile interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneProfile(r randyProfile) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringProfile(r randyProfile) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneProfile(r)
	}
	return string(tmps)
}
func randUnrecognizedProfile(r randyProfile, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldProfile(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldProfile(dAtA []byte, r randyProfile, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateProfile(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateProfile(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func init() { proto.RegisterFile("pb/profile.proto", fileDescriptorProfile) }

var fileDescriptorProfile = []byte{
	// 1259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xac, 0xd7, 0x6b, 0xe7, 0xa5, 0x49, 0xdc, 0x29, 0xa2, 0x6e, 0x28, 0x49, 0xba, 0xa4,
	0xe0, 0x24, 0x5d, 0xaf, 0xd7, 0x29, 0x55, 0x52, 0x40, 0xa9, 0x0d, 0x4d, 0xa9, 0xda, 0xa4, 0xd5,
	0x5a, 0x2d, 0xa2, 0x8e, 0x1b, 0xd6, 0xf6, 0xd8, 0x59, 0x62, 0x7b, 0x96, 0x9d, 0xb5, 0xdb, 0x26,
	0x36, 0x07, 0x90, 0xca, 0x09, 0x71, 0xe8, 0x01, 0x71, 0x45, 0x20, 0xa1, 0x2a, 0x07, 0x8e, 0xe5,
	0xc8, 0x35, 0x57, 0xce, 0x28, 0xc2, 0xe2, 0xc2, 0x7f, 0xc0, 0x11, 0xed, 0xec, 0xda, 0x71, 0x52,
	0x11, 0x1c, 0x05, 0x51, 0x71, 0xf2, 0xfc, 0x78, 0xef, 0x7d, 0xdf, 0xcc, 0xfb, 0xf6, 0xbd, 0x31,
	0x44, 0xac, 0xbc, 0x6a, 0xd9, 0xb4, 0x64, 0x56, 0x48, 0xdc, 0xb2, 0xa9, 0x43, 0xf1, 0x2b, 0x65,
	0xdb, 0x2a, 0xc4, 0xcb, 0xb4, 0x4a, 0x88, 0x43, 0x1e, 0x1a, 0x55, 0xab, 0x42, 0x58, 0xdc, 0x37,
	0x19, 0x3b, 0x5b, 0xa6, 0xb4, 0x5c, 0x21, 0xaa, 0x61, 0x99, 0xaa, 0x51, 0xab, 0x51, 0xc7, 0x70,
	0x4c, 0x5a, 0x63, 0x9e, 0xeb, 0xd8, 0xa5, 0xb2, 0xe9, 0xac, 0xd7, 0xf3, 0xf1, 0x02, 0xad, 0xaa,
	0xd5, 0x07, 0xa6, 0xb3, 0x41, 0x1f, 0xa8, 0x65, 0xaa, 0xf0, 0x4d, 0xa5, 0x61, 0x54, 0xcc, 0xa2,
	0xe1, 0x50, 0x9b, 0xa9, 0xdd, 0xa1, 0xef, 0x37, 0xdf, 0xe3, 0xe7, 0x01, 0xef, 0xb9, 0x79, 0xf3,
	0x92, 0xb1, 0x41, 0x6c, 0xb5, 0x67, 0xec, 0x7b, 0x2a, 0xfb, 0x3c, 0xcb, 0x54, 0xe5, 0xcb, 0xf9,
	0x7a, 0x89, 0xcf, 0xf8, 0x84, 0x8f, 0x3c, 0x73, 0x79, 0x04, 0x4e, 0x5c, 0xad, 0x5a, 0xce, 0xa3,
	0x65, 0xc2, 0x98, 0x51, 0x26, 0x72, 0x06, 0x46, 0xef, 0x12, 0x9b, 0x99, 0xb4, 0xa6, 0x13, 0x66,
	0xd1, 0x1a, 0x23, 0xf8, 0x2c, 0x88, 0x35, 0xa3, 0x4a, 0xa2, 0x68, 0x12, 0xc5, 0x06, 0xd3, 0xe1,
	0x9d, 0x6d, 0x49, 0x9c, 0x11, 0x22, 0x48, 0xe7, 0xab, 0x58, 0x86, 0x50, 0xc3, 0x73, 0x88, 0x0a,
	0xbd, 0x06, 0x51, 0xa4, 0x77, 0x36, 0xe4, 0x5f, 0x11, 0x0c, 0x67, 0x88, 0xdd, 0x30, 0x0b, 0x24,
	0xe3, 0x18, 0x4e, 0x9d, 0x1d, 0x3f, 0x26, 0xbe, 0x0e, 0x12, 0xe3, 0xb1, 0xa2, 0x81, 0x49, 0x14,
	0x1b, 0x49, 0x6a, 0xf1, 0x43, 0xb2, 0x14, 0xdf, 0x87, 0x1e, 0xf7, 0x7e, 0x74, 0x3f, 0x00, 0x3e,
	0x0b, 0x41, 0xb2, 0x56, 0x65, 0xe5, 0xa8, 0xc8, 0xc1, 0x42, 0x3b, 0xdb, 0x52, 0xe0, 0x19, 0x42,
	0xba, 0x48, 0x96, 0x59, 0x59, 0x3e, 0x07, 0x92, 0x4f, 0x5a, 0x02, 0xe1, 0xd6, 0x8d, 0xc8, 0x00,
	0x1e, 0x85, 0xa1, 0x3b, 0x2b, 0xa9, 0xbb, 0xa9, 0xeb, 0x37, 0x53, 0xe9, 0x9b, 0x57, 0x23, 0x48,
	0x5e, 0x05, 0xec, 0x03, 0x30, 0xcf, 0xf4, 0xa6, 0xc9, 0x1c, 0xbc, 0x04, 0x61, 0xe6, 0xaf, 0x46,
	0xd1, 0x64, 0x20, 0x36, 0x94, 0x9c, 0xe9, 0x9f, 0xa3, 0xde, 0xf5, 0x95, 0xbf, 0x11, 0x61, 0xe8,
	0xb6, 0x67, 0x73, 0xbd, 0x56, 0xa2, 0xb8, 0x05, 0x62, 0xbd, 0x6e, 0x16, 0xfd, 0xbb, 0x33, 0x77,
	0xb6, 0x25, 0x09, 0x8b, 0x58, 0xb8, 0x7b, 0xb1, 0xbd, 0x3b, 0x91, 0x85, 0x0f, 0xef, 0x67, 0x0d,
	0xa5, 0x94, 0x52, 0x96, 0x12, 0xca, 0x42, 0x6e, 0x6b, 0xbe, 0xa5, 0xf4, 0x4e, 0x2f, 0xb6, 0x94,
	0x8b, 0xbd, 0xf3, 0xb9, 0x96, 0x92, 0x9d, 0x6f, 0x2e, 0x34, 0x8d, 0x54, 0x33, 0x9f, 0xce, 0x1d,
	0xdc, 0xe9, 0x99, 0x6a, 0xc9, 0xd6, 0x94, 0xce, 0x61, 0xf1, 0x12, 0x48, 0x65, 0x52, 0x2b, 0x12,
	0x9b, 0xe7, 0x66, 0x24, 0x39, 0x75, 0xe8, 0xa1, 0xae, 0x71, 0x53, 0xe6, 0x65, 0x70, 0x4c, 0x98,
	0x47, 0xba, 0xef, 0x8d, 0x9f, 0x22, 0x08, 0x92, 0xaa, 0x61, 0x56, 0x78, 0x02, 0x07, 0xd3, 0x4f,
	0x90, 0x6b, 0xb2, 0x29, 0x44, 0x50, 0x7b, 0x77, 0xe2, 0x31, 0x82, 0xcf, 0x91, 0x7b, 0x92, 0xcd,
	0x94, 0x72, 0x2f, 0xa1, 0x2c, 0xc4, 0xcf, 0xbd, 0x36, 0x75, 0xfe, 0xf5, 0x37, 0x66, 0x66, 0xd5,
	0x77, 0x16, 0xef, 0xaf, 0x6d, 0x35, 0x5b, 0x9f, 0x2a, 0xb9, 0xd9, 0x2b, 0x7b, 0xfb, 0xb9, 0xd8,
	0xe2, 0xe5, 0xbd, 0x99, 0x92, 0xdb, 0x4a, 0x5c, 0xb8, 0xa4, 0xb5, 0x7a, 0xf6, 0xa7, 0x17, 0x63,
	0x8b, 0x97, 0x57, 0xe3, 0x47, 0xf2, 0x98, 0x9e, 0x99, 0xd2, 0x3d, 0x8a, 0xf8, 0xbc, 0xaf, 0x57,
	0x4f, 0x21, 0x27, 0x3d, 0xa6, 0x31, 0x97, 0x69, 0xd0, 0x42, 0x0f, 0xbf, 0xee, 0x08, 0x97, 0x42,
	0x38, 0x6f, 0xda, 0xce, 0x7a, 0xd1, 0x78, 0x14, 0x0d, 0x72, 0xd3, 0xcc, 0xce, 0xb6, 0x34, 0xf8,
	0x14, 0x49, 0x49, 0x31, 0x7c, 0x32, 0x52, 0x68, 0xef, 0x4e, 0xa4, 0xe1, 0xca, 0xfd, 0x98, 0xb6,
	0xd0, 0x4c, 0x26, 0xa6, 0x57, 0x8b, 0xab, 0xc5, 0xac, 0x32, 0xa9, 0xc6, 0x73, 0xb1, 0x44, 0x56,
	0x53, 0x16, 0x72, 0x4d, 0x2d, 0x9b, 0xd0, 0x92, 0xb9, 0xe9, 0xfd, 0x8b, 0x59, 0x2d, 0x99, 0xcb,
	0xba, 0x8c, 0x9a, 0x73, 0xd9, 0x84, 0x96, 0x9b, 0x9e, 0xd2, 0xbb, 0x20, 0xf2, 0x57, 0x08, 0x46,
	0x7c, 0x6d, 0xe8, 0xe4, 0x93, 0x3a, 0x61, 0xce, 0x0b, 0x96, 0x87, 0xfc, 0x31, 0x8c, 0x76, 0x09,
	0xf9, 0x05, 0xe4, 0x0c, 0x08, 0x74, 0x83, 0xf3, 0x09, 0xa7, 0x07, 0x77, 0xb6, 0xa5, 0x20, 0x04,
	0x30, 0xd2, 0x74, 0x81, 0x6e, 0xe0, 0xb7, 0x41, 0x34, 0x6b, 0x25, 0xca, 0xa5, 0x34, 0x94, 0x8c,
	0x1d, 0x2a, 0xa5, 0x9e, 0x6f, 0x40, 0xe7, 0x5e, 0xf2, 0xf7, 0x01, 0x78, 0xd9, 0x5f, 0x7d, 0xd7,
	0x26, 0xbc, 0xf0, 0x76, 0x6e, 0x61, 0x4f, 0xa5, 0xe8, 0x5f, 0x52, 0xa9, 0xf0, 0xff, 0x51, 0x69,
	0xa0, 0x7f, 0x95, 0x8a, 0xff, 0x85, 0x4a, 0x7f, 0x46, 0x80, 0xfd, 0x3c, 0xb9, 0x95, 0xb1, 0x93,
	0xa3, 0x04, 0x0c, 0x59, 0x46, 0x99, 0xac, 0xd5, 0xea, 0xd5, 0xbc, 0x9f, 0xa8, 0xe1, 0xf4, 0x68,
	0x57, 0x20, 0xed, 0xdd, 0x09, 0x21, 0x32, 0xa0, 0x83, 0x6b, 0xb3, 0xc2, 0x4d, 0xb0, 0x06, 0x83,
	0xdc, 0x83, 0x99, 0x9b, 0x84, 0x27, 0x64, 0x38, 0xfd, 0xd2, 0xce, 0xb6, 0x14, 0x82, 0x20, 0x0e,
	0x24, 0x13, 0x09, 0xf7, 0xa0, 0x91, 0x81, 0xe8, 0x1f, 0x21, 0x3d, 0xec, 0x9a, 0x65, 0xcc, 0x4d,
	0xd2, 0x23, 0x84, 0xc0, 0x71, 0x84, 0x20, 0xff, 0x84, 0xba, 0x55, 0x98, 0x57, 0x77, 0x0d, 0x46,
	0x6d, 0xc2, 0xea, 0x15, 0x67, 0x8d, 0x11, 0xc7, 0x23, 0xe4, 0x1d, 0xa0, 0xab, 0xf0, 0x37, 0xf5,
	0x61, 0xcf, 0x22, 0x43, 0x1c, 0x4e, 0x25, 0x06, 0xe1, 0x75, 0x83, 0xad, 0x55, 0xa9, 0xed, 0x91,
	0x0f, 0xa7, 0x87, 0xdd, 0x7b, 0x87, 0x10, 0x0e, 0x96, 0x8c, 0x0a, 0x23, 0x7a, 0x68, 0xdd, 0x60,
	0xcb, 0xd4, 0x26, 0x78, 0x19, 0xc2, 0x3e, 0x23, 0xb7, 0xbd, 0x05, 0x8e, 0xf2, 0x69, 0x78, 0xed,
	0xeb, 0x47, 0x14, 0xd4, 0xbb, 0x21, 0x66, 0x66, 0x21, 0xe4, 0x1f, 0x0c, 0x03, 0x48, 0x77, 0x56,
	0x6e, 0xac, 0xdc, 0xfa, 0x20, 0x32, 0x80, 0xc3, 0x20, 0x2e, 0xa7, 0xdc, 0x06, 0xe6, 0xae, 0x2e,
	0x5d, 0xe5, 0x63, 0x21, 0xf9, 0x5d, 0x18, 0x42, 0x7e, 0x3c, 0xbc, 0x05, 0x21, 0xff, 0x35, 0x80,
	0xa7, 0x0f, 0x25, 0xd0, 0xfb, 0x86, 0x18, 0xbb, 0x70, 0xa8, 0xe9, 0x81, 0xe7, 0x85, 0x7c, 0xfa,
	0xb3, 0x5f, 0x7e, 0x7f, 0x22, 0x9c, 0xc4, 0xa3, 0xfc, 0x09, 0xd5, 0xd0, 0xd4, 0x4e, 0x87, 0xff,
	0x12, 0xc1, 0xc8, 0xfe, 0xb6, 0x7a, 0x14, 0x12, 0x6a, 0x3f, 0xbd, 0xb6, 0xa7, 0x5d, 0xcb, 0x13,
	0x9c, 0xc7, 0x19, 0x7c, 0xba, 0xc3, 0xa3, 0xd3, 0x80, 0x55, 0xff, 0x99, 0xf0, 0x18, 0x81, 0xc4,
	0xcb, 0x0c, 0xc1, 0x73, 0xfd, 0x64, 0xe3, 0x40, 0x49, 0xfa, 0x87, 0x6b, 0x39, 0x50, 0x34, 0xe5,
	0x33, 0x9c, 0xce, 0x29, 0x79, 0xa4, 0x43, 0xa7, 0xc0, 0xa1, 0x2f, 0xa3, 0x19, 0xdc, 0x00, 0x51,
	0x27, 0x46, 0x11, 0xcf, 0xf6, 0x17, 0xd0, 0x43, 0xef, 0x5b, 0x40, 0x9d, 0x84, 0xc8, 0x27, 0x3a,
	0xc8, 0x36, 0x31, 0x8a, 0x2e, 0xee, 0x26, 0x88, 0x5c, 0xfa, 0x6a, 0x3f, 0xa1, 0x7a, 0x3e, 0xf4,
	0xfe, 0xb0, 0x79, 0x12, 0x9e, 0xc3, 0xae, 0x98, 0xcc, 0x71, 0xb1, 0xb7, 0x40, 0xba, 0x63, 0x15,
	0xdd, 0xbb, 0xef, 0xfb, 0x20, 0xc7, 0xbd, 0xf0, 0x3a, 0xc7, 0x73, 0xc1, 0xbf, 0x40, 0x00, 0x19,
	0x5a, 0x72, 0xde, 0x23, 0x15, 0xe2, 0x90, 0xa3, 0xdd, 0xfb, 0xd1, 0x48, 0x8c, 0x73, 0x12, 0x51,
	0xf9, 0x54, 0x57, 0x84, 0xb4, 0xe4, 0xac, 0x15, 0x39, 0x6e, 0x87, 0xc9, 0xfb, 0x86, 0x5d, 0x7c,
	0x01, 0x4c, 0xd6, 0x0d, 0xbb, 0xb8, 0xc7, 0x24, 0xfd, 0xd1, 0x9f, 0xbf, 0x8d, 0xa3, 0x1f, 0xda,
	0xe3, 0xe8, 0x59, 0x7b, 0x1c, 0xc1, 0xab, 0x05, 0x5a, 0xfd, 0xbb, 0xc8, 0x0d, 0xed, 0xde, 0x85,
	0xe7, 0xfe, 0xce, 0x28, 0x1d, 0x33, 0x95, 0x35, 0x0a, 0x8a, 0x6f, 0xaa, 0x5a, 0xf9, 0xb7, 0xac,
	0xfc, 0xb7, 0x82, 0x78, 0x6d, 0xf9, 0x76, 0x3a, 0x2f, 0xf1, 0x7f, 0x28, 0x73, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x5d, 0x42, 0x20, 0xce, 0x91, 0x0d, 0x00, 0x00,
}
