// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package pb

const (
	// SwaggerURL is the url for swagger.json
	SwaggerURL = "/api/v1/swagger.json"

	// Swagger expose the json representation
	Swagger = swagger
)

//go:generate go run generator/main.go
