// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/profile.proto
package models

import (
	"fmt"
	"strings"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

func MigrateSchema(dsn string) error {

	if strings.Contains(dsn, "?") {
		return fmt.Errorf("database connection error: data source name cannot contain options")
	}
	dsn = fmt.Sprintf("%s?charset=utf8&parseTime=True", dsn)

	db, err := gorm.Open("mysql", dsn)
	if err != nil {
		return fmt.Errorf("Mysql database connection error: %v", err)
	}
	mdls := mysqlModels()
	if len(mdls) > 0 {
		db.Set("gorm:table_options", fmt.Sprintf("ENGINE=%s", "InnoDB")).AutoMigrate(mdls...)

		for _, mdl := range mdls {
			if !db.HasTable(mdl) {
				return fmt.Errorf("Schema migration error: the %v table does not exist", mdl)
			}
		}
	}

	return nil
}
